"""Orders repositories (placeholders)."""
from typing import Protocol, Iterable, Optional
from .models import Order


class OrderRepository(Protocol):
    def create(self, order: Order) -> int: ...
    def get(self, order_id: int) -> Optional[Order]: ...
    def update_status(self, order_id: int, status: str) -> None: ...
    def list_by_encounter(self, encounter_id: int) -> Iterable[Order]: ...

