"""EHR repositories (placeholders)."""
from typing import Protocol, Iterable, Optional
from .models import Encounter, Problem, Allergy, Medication


class EncounterRepository(Protocol):
    def create(self, enc: Encounter) -> int: ...
    def get(self, encounter_id: int) -> Optional[Encounter]: ...


class ProblemRepository(Protocol):
    def append(self, problem: Problem) -> int: ...
    def list_by_patient(self, patient_id: int) -> Iterable[Problem]: ...


class AllergyRepository(Protocol):
    def append(self, allergy: Allergy) -> int: ...
    def list_by_patient(self, patient_id: int) -> Iterable[Allergy]: ...


class MedicationRepository(Protocol):
    def append(self, medication: Medication) -> int: ...
    def list_by_patient(self, patient_id: int) -> Iterable[Medication]: ...

